base:
  project: demo-project-iris
  tags: [dev]
  experiments:
    experiments_folder: experiments
  model:
    model_name: model.joblib
    models_folder: experiments/models
  random_state: 42 # random state for train/test split


data_load:
  raw_data_path: data/raw/iris.csv


featurize:
  features_path: data/processed/features.csv
  target_column: target


data_split:
  test_size: 0.2
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv


train:
  cv: 5
  estimator_name: logreg
  estimators:
    logreg: # sklearn.linear_model.LogisticRegression
      param_grid:
        C: [0.001]
        solver: ["lbfgs"]
        multi_class: ["multinomial"]
        max_iter: [100]

    svm: # sklearn.svm.SVC
      param_grid:
        C: [0.1, 1.0]
        kernel: ["rbf", "linear"]
        gamma: ["scale"]
        degree: [3, 5]


evaluate:
  metrics_file: metrics.json
  confusion_matrix_png: confusion_matrix.png
  classes_path: classess.csv
